SIM ?= verilator
TOPLEVEL_LANG ?= verilog
SIM_BUILD = sim_build_di_sigmoid

VERILOG_SOURCES += $(PWD)/../../rtl/di_exp.sv
VERILOG_SOURCES += $(PWD)/../../rtl/di_sigmoid.sv

TOPLEVEL = di_sigmoid
MODULE = test_di_sigmoid

ifeq ($(SIM),verilator)
EXTRA_ARGS += --trace --trace-structs -Wno-fatal
endif

export PYTHONPATH := $(PWD)/../..:$(PWD)/../../software/compiler:$(PYTHONPATH)

include $(shell cocotb-config --makefiles)/Makefile.sim
