# Makefile for valid chain CocoTB simulation

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = $(PWD)/../../rtl/defines.sv
VERILOG_SOURCES += $(PWD)/../../rtl/skewer.sv

TOPLEVEL = streaming_skewer

MODULE = test_valid_chain

ifeq ($(SIM),verilator)
    COMPILE_ARGS += -I$(PWD)/../../rtl -Wno-fatal
else
    COMPILE_ARGS += -g2012 -I$(PWD)/../../rtl
endif

SIM_ARGS += -lx2

include $(shell cocotb-config --makefiles)/Makefile.sim
